#include "prime_2.h"

bool initialized = false;
long nth_prime[N_PRIMES];
bool primes[P_LIMIT];

//Fills the factors array with the prime factors of the number
void prime_factors(long num, int *factors)
{
    bool first_check = true;
    int curr_prime_index = 0;
    while(num != 1)
    {
	if(first_check)
	{
	    factors[curr_prime_index] = 0;
	    first_check = false;
	}

	if(num % prime(curr_prime_index) == 0)
	{
	    num = num / prime(curr_prime_index);
	    factors[curr_prime_index] = factors[curr_prime_index] + 1;
	}
	else
	{
	    curr_prime_index++;
	    first_check = true;
	}
    }
    factors[++curr_prime_index] = -1;
    return;
}

//Returns true if a number is prime, O(sqrt(n))
//This naive algorithm works by trial division rather than anything fancy.
//Answers are cached and optionally pre-generated by initialize_primes()
bool is_prime(long long num)
{
    if(initialized && num < P_LIMIT)
    {
#ifdef DEBUG_PRIME
	printf("Cached!\n");
#endif
	return primes[num];
    }
    
    if(num == 1 || num <= 0) return false;

    long max = ceil(sqrt(num));
    long n = 2;
    bool prime = true;

    while(n <= max)
    {
	if(num % n == 0 && num != n)
	{
	    prime = false;
	    break;
	}
	n++;
    }
     
    return prime;
}

//Returns the nth prime number
long prime(int n)
{
    if(initialized && n < N_PRIMES)
    {
	return nth_prime[n];
    }
    else
    {
	printf("Error!\n");
	return -1;
    }
}

/*
  Initialized the primes and nth_prime arrays by getting all the primes up to P_LIMIT
 */
void initialize_primes(void)
{
    if(initialized) return;
    int i = 0;
    long n = 2; 
    while(n < P_LIMIT || i < N_PRIMES)
    {
	bool curr_b = is_prime(n);
	if(n < P_LIMIT)
	{
	    primes[n] = curr_b;
	}
	if(curr_b && i < N_PRIMES)
	{
	    nth_prime[i] = n;
	    i++;
	}
	n++;
    }
    initialized = true;
}


//Returns the number of digits in the number
int n_digits(long n)
{
    return ceil(log(n)/log(10));
}


//Returns the first prime after p
long next_prime(long p)
{
    //if p is even, add one. if p is odd, add two.
    p += (p % 2 == 0) ? 1 : 2;
    while(!is_prime(p))
    {
	p += 2;
    }
    return p;
}
